title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "윤종근"

phone_number: 010-4641-3018
address: Incheon, South Korea
email: doodukly1999@gmail.com
linkedin_username: https://www.linkedin.com/in/jonggeun-yoon-a94126335/
github_username: https://github.com/hi2242

baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag